apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
     # imagePullSecrets:
    #  - name: ecr-registry-secret
      containers:
      - name: frontend
        image: public.ecr.aws/m3y4k5f3/frontend:7
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "https://backend.app.soclabs.cm/api/tasks"
        ports:
        - containerPort: 3000
